version: '3.2'

services:

  registry:
    image: registry:${REGISTRY_VERSION:-2}
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=${REGISTRY_DOMAIN:-registry.localdomain}
    volumes:
      - docker-registry:/var/lib/registry
      - docker-registry-auth:/auth
    deploy:
      labels:
        - traefik.docker.network=proxy
        - traefik.domain=${REGISTRY_DOMAIN:-registry.localdomain}
        - traefik.enable=true
        - traefik.port=5000
        - traefik.frontend.rule=Host:${REGISTRY_DOMAIN:-registry.localdomain}
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure            
    networks:
      - proxy

  frontend:
    image: konradkleine/docker-registry-frontend:v2
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
    deploy:
      labels:
        - traefik.docker.network=proxy
        - traefik.domain=${REGISTRYFE_DOMAIN:-registryfe.localdomain}
        - traefik.enable=true
        - traefik.port=80
        - traefik.frontend.rule=Host:${REGISTRYFE_DOMAIN:-registryfe.localdomain}
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure            
    networks:
      - proxy
    

volumes:
  docker-registry:
    external: true

  docker-registry-auth:
    external: true

networks:
  proxy:
    external: true